# Generated by Django 4.1.3 on 2022-11-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_name_myuser_first_name_myuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
