# Generated by Django 4.1.3 on 2022-12-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_myuser_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='education_background',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='establish_date',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='interest',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
